from __future__ import annotations

from collections.abc import Iterable
from time import perf_counter

from app.ai.exceptions import PlanningException
from app.ai.intent_engine import IntentEngine
from app.ai.planner.execution_plan import ExecutionPlan
from app.ai.planner.planner_context import PlannerContext
from app.ai.planner.planning_strategy import PlanningStrategy
from app.ai.planner.rule_based_planner import RuleBasedPlanner
from app.core.logging import get_logger


logger = get_logger(__name__)


class ReasoningPlanner:
    """
    Orchestrate planning for reasoning requests.

    The planner is responsible for intent detection, context assembly,
    and delegating plan construction to a pluggable planning strategy.
    """

    def __init__(
        self,
        strategy: PlanningStrategy | None = None,
        available_tools: Iterable[str] | None = None,
    ) -> None:
        self.strategy = strategy or RuleBasedPlanner()
        self.available_tools = tuple(
            available_tools or (
                "inventory",
                "warehouse",
                "shipment",
                "procurement",
                "ai_insights",
            )
        )

    def build_plan(self, message: str) -> ExecutionPlan:
        """
        Detect intent, build planner context, and delegate plan creation.

        Args:
            message: Raw user request.

        Returns:
            An execution plan generated by the configured strategy.
        """
        logger.info("Incoming planning request: %s", message)
        started_at = perf_counter()

        try:
            context = PlannerContext(
                user_message=message,
                detected_intent=IntentEngine.detect(message),
                available_tools=self.available_tools,
            )

            logger.info(
                "Planning context prepared with intent=%s and tools=%s",
                context.detected_intent,
                list(context.available_tools),
            )

            plan = self.strategy.build_plan(context)

            logger.info(
                "Execution plan created: tools=%s reasoning=%s duration_ms=%.2f",
                plan.tools,
                plan.reasoning,
                (perf_counter() - started_at) * 1000,
            )

            return plan
        except Exception as exc:
            logger.exception("Planning failed for request: %s", message)
            raise PlanningException(
                "Unable to build an execution plan."
            ) from exc
